random_state: 993
data_path: 'data/'
files: ['chronom', 'chugun', 'reduced_gas', 'lom', 'plavki', 'reduced_produv', 'sip', 'cat_lom', 'cat_sip']
model_tst_path: 'model_tst'
model_C_path: 'model_C'
submission_path: 'first_submission.csv'